#!/usr/bin/env bash
#
# gen-readme-index.sh — regenerate the problem index in README.md.
#
# For every topic folder it lists the individual problems as links to their
# source files (class names prettified, e.g. ContainerWithMostWater ->
# "Container With Most Water"). Each category is a collapsible <details> block.
# It rewrites only the region between the <!-- INDEX:START --> and
# <!-- INDEX:END --> markers, and never moves, renames, or deletes any file.
#
# Usage:  ./scripts/gen-readme-index.sh   (run from anywhere)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

README="README.md"
BASE="src/main/java/com/abn"
START="<!-- INDEX:START -->"
END="<!-- INDEX:END -->"

# Count *.java under a folder (recursive; 0 if missing).
count() { find "$1" -name '*.java' 2>/dev/null | wc -l | tr -d ' '; }

# Turn a Java class name into a readable title.
prettify() {
  printf '%s' "$1" | perl -pe 's/([a-z0-9])([A-Z])/$1 $2/g; s/([A-Z]+)([A-Z][a-z])/$1 $2/g; s/^([a-z])/\U$1/'
}

# Print "- [Pretty Name](path)" for each .java file in a folder.
#   mode "flat" -> only files directly in the folder (maxdepth 1)
#   mode "deep" -> all files recursively (for folders with sub-packages)
emit_links() {
  local folder="$1" mode="$2" f base
  local -a args=()
  [ "$mode" = "flat" ] && args=(-maxdepth 1)
  find "$folder" ${args[@]+"${args[@]}"} -name '*.java' 2>/dev/null | sort | while IFS= read -r f; do
    base="$(basename "$f" .java)"
    printf -- '- [%s](%s)\n' "$(prettify "$base")" "$f"
  done
}

# Emit one collapsible category. Skips empty/missing folders.
catblock() {
  local label="$1" folder="$2" mode="${3:-flat}"
  [ -d "$folder" ] || return 0
  local links; links="$(emit_links "$folder" "$mode")"
  [ -z "$links" ] && return 0
  printf '<details><summary><b>%s</b></summary>\n\n%s\n\n</details>\n\n' "$label" "$links"
}

gen() {
  local total; total="$(count src)"

  echo "$START"
  echo
  echo "> Auto-generated by \`scripts/gen-readme-index.sh\` from **$total** Java files. Do not edit this block by hand; run the script instead. Click any category to expand its problems."
  echo

  # ---- Repository map -------------------------------------------------------
  echo "### Repository Map"
  echo
  echo "| Area | Focus |"
  echo "| --- | --- |"
  printf '| [Data Structures & Algorithms](%s) | Pattern-grouped algorithms, structure problems, core DS implementations |\n' "$BASE/dsalgos"
  printf '| [Scaler DSA](%s) | Day-by-day course practice |\n' "$BASE/scaler"
  printf '| [Design](%s) | Low-level design, patterns, and design-round problems |\n' "$BASE/design"
  echo

  # ---- Algorithms by pattern ------------------------------------------------
  echo "### Algorithms — by pattern"
  echo
  local A="$BASE/dsalgos/algo"
  catblock "Dynamic Programming"   "$A/dp"
  catblock "Backtracking"          "$A/backtrack"
  catblock "Two Pointers"          "$A/twoPointers"
  catblock "DFS"                   "$A/DFS"
  catblock "BFS"                   "$A/BFS"
  catblock "Sliding Window"        "$A/slidingWindo"
  catblock "Recursion"             "$A/recursion"
  catblock "Greedy"                "$A/greedy"
  catblock "Heap / Priority Queue" "$A/heap"
  catblock "Binary Search"         "$A/binarySearch"
  catblock "Bitwise"               "$A/bitwise"
  catblock "Merge Intervals"       "$A/mergeIntervals"
  catblock "Cyclic Sort"           "$A/cyclicSort"
  catblock "Subsets"               "$A/subset"
  catblock "K-way Merge"           "$A/kwayMerge"
  catblock "Merge"                 "$A/merge"
  catblock "Other (uncategorized)" "$A" flat   # loose files directly in algo/

  # ---- Data-structure problems ----------------------------------------------
  echo "### Data-Structure Problems"
  echo
  local C="$BASE/dsalgos/datastructure"
  catblock "Linked List" "$C/linkedList"
  catblock "String"      "$C/string"
  catblock "Assorted"    "$C/problems"
  catblock "Binary Tree" "$C/binaryTree"
  catblock "Stack"       "$C/stack"
  catblock "Graph"       "$C/graph"
  catblock "Trie"        "$C/trie"
  catblock "BST"         "$C/BST"
  catblock "Heap"        "$C/heap"
  catblock "Queue"       "$C/queue"
  catblock "Sort"        "$C/sort"
  catblock "N-ary Tree"  "$C/NaryTree"

  # ---- Core data structure implementations ----------------------------------
  echo "### Core Data-Structure Implementations"
  echo
  echo "From-scratch implementations."
  echo
  local D="$BASE/dsalgos/datastructure/dsImpl"
  catblock "Linked List" "$D/linkedList"
  catblock "Binary Tree" "$D/binaryTree"
  catblock "Queue"       "$D/queue"
  catblock "Stack"       "$D/stack"
  catblock "Graph"       "$D/graph"
  catblock "Trie"        "$D/trie"

  # ---- Other DSA sets -------------------------------------------------------
  echo "### Other Practice Sets"
  echo
  local G="$BASE/dsalgos"
  catblock "Interview Problems" "$G/problems" flat
  catblock "To-Do"              "$G/problems/toDo"
  catblock "Cockroach"          "$G/cockroach"
  catblock "Sorting Algorithms" "$G/sortAlgos"
  catblock "Codility"           "$G/codility"

  # ---- Scaler DSA -----------------------------------------------------------
  echo "### Scaler DSA — by day"
  echo
  local day
  for day in $(find "$BASE/scaler/dsa" -maxdepth 1 -type d | tail -n +2 | sort -V); do
    catblock "$(basename "$day")" "$day" flat
  done

  # ---- Design ---------------------------------------------------------------
  echo "### Design"
  echo
  local L="$BASE/design"
  catblock "Notification System (LLD)" "$L/LLD/notification" deep
  catblock "Library Mgmt System (LLD)" "$L/LLD/lbms"         deep
  catblock "Test Runner (LLD)"         "$L/LLD/testRunner"   deep
  catblock "Producer / Consumer"       "$L/prodconsumer"     deep
  catblock "LeetCode (design)"         "$L/leetcode"         deep
  catblock "Singleton"                 "$L/singleton"        deep
  catblock "Design Patterns"           "$L/designPatterns"   deep

  echo "$END"
}

# gen() prints the full block INCLUDING the START and END marker lines.
# Replace the existing marker region in README.md with the freshly generated one,
# keeping all prose before START and after END untouched.
if ! grep -qF "$START" "$README" || ! grep -qF "$END" "$README"; then
  echo "error: markers $START / $END not found in $README" >&2
  exit 1
fi

block="$(mktemp)"
gen > "$block"

tmp="$(mktemp)"
BLOCK="$block" awk -v start="$START" -v end="$END" '
  index($0, start) { while ((getline line < ENVIRON["BLOCK"]) > 0) print line; skip=1; next }
  index($0, end)   { skip=0; next }
  skip != 1        { print }
' "$README" > "$tmp"

mv "$tmp" "$README"
rm -f "$block"
echo "README.md problem index regenerated ($(count src) Java files)."
